apiVersion: v1
kind: Pod
metadata:
  name: multi-contaner  
spec:
  # list of containers
  containers:
  - name: nginx
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep", "300"]
